### ISSUE TITLE
Error: Cannot find module 'node:crypto' when I upgrade uuid version from 9.0.0. to 10.0.0

### ISSUE THREAD

**Issue by chengmo03013106** [uuidjs/uuid#765]
### Feature description

Error: Cannot find module 'node:crypto' when I upgrade uuid version from 9.0.0. to 10.0.0

### Additional information

npm version 6.13.7
node version v12.14.1

**Comment by ctavan** [comment]
As the [release notes](https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md) state, support for Node.js 12 and 14 was dropped with the 10.x release.

The options are to either upgrade to a current Node.js LTS release or pin the uuid package to 9.x

**Comment by andrmoel** [comment]
Got the same issue with node 20. When I know more I'll update you

**Comment by bigboydiamonds** [comment]
Seeing a similar issue with Node v18.X

**Comment by broofa** [comment]
@andrmoel @bigboydiamonds et al...

If/when you can reproduce this issue, please open a new Issue (bug report, not feature request!).. but pay close attention to the verbiage in issue template about needing a _**with a minimal, complete, and verifiable**_ example.
